name: Node.js Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npm test
      - run: npm run build
